nebula/nebula/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('webay.urls'))
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

nebula/webay/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views

# will deleteItemView and DeleteView

app_name = 'webay'

urlpatterns = [
    path('', views.index, name='homepage'),
    path('item/<int:item_id>/', views.item_view, name='item-detail'),
    path('getAllBids/<int:item_id>/', views.get_all_bids, name='get_all_bids'),
    path('openauctions/', views.auctions, name='auctions'),
    path('closedauctions/', views.closed_auctions, name='closedauctions'),
    path('register/', views.register, name='register'),
    path('profile/', views.profile, name='profile'),
    path('getUserDetails/', views.get_user_details, name='get_user_details'),
    path('updateProfile/', views.update_profile_details, name='update_profile_details'),
    path('updateProfilePic/', views.update_profile_pic, name='update_profile_pic'),
    path('getNotifications/', views.get_notifications, name='get_messages'),
    path('getNotificationMessage/<int:id>', views.get_notifications_message, name='get_notifications_message'),
    path('markNotificationAsRead/<int:id>', views.mark_notification_as_read, name='mark_notif_read'),
    path('getUnreadNotifNumber/', views.get_number_unread_notifs, name='get_number_unread_notifs'),
    path('notifications/', views.display_profile_table, name='display_notifications'),
    path('login/', auth_views.LoginView.as_view(template_name='webay/login.html'), name='login'),
    path('logout/', views.logout, name="logout"),
    path('additem/', views.add_item, name='additem'),
    path('search/', views.search, name='search'),
    path('getMyItems/', views.get_my_items, name='myitems'),
    path('myItems/', views.display_profile_table, name='display_my_items')
]

nebula/webay/models.py
from django.contrib.auth.models import User
from django.core.validators import RegexValidator
from django.db import models


# Create your models here.


class Item(models.Model):
    title = models.CharField(max_length=255)
    description = models.CharField(max_length=500)
    item_pic = models.ImageField(upload_to='webay/media/item_pics')
    base_price = models.DecimalField(max_digits=10, decimal_places=2)
    start_datetime = models.DateTimeField('%d/%m/%Y %H:%M:%S')
    end_datetime = models.DateTimeField('%d/%m/%Y %H:%M:%S')
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title


class Bid(models.Model):
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    bid_datetime = models.DateTimeField('%d/%m/%Y %H:%M:%S')
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE, to_field="username")

    def __str__(self):
        return self.item.title


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    dob = models.DateField()
    profile_pic = models.ImageField(default='default.jpg', upload_to='webay/media/profile_pics')
    address = models.CharField(max_length=255)
    mobile_regex = RegexValidator(regex=r'^0\d{10}$', message='Mobile number must be a valid 11 digit UK number.')
    mobile = models.CharField(validators=[mobile_regex], max_length=11)

    def __str__(self):
        return self.user.username


class Notification(models.Model):
    recipient = models.ForeignKey(User, on_delete=models.CASCADE, related_name='notification')
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    message = models.TextField()
    email_sent = models.BooleanField()
    read_message = models.BooleanField()

nebula/webay/forms.py
from django import forms
from django.contrib.auth.models import User
from webay.models import UserProfile, Item


class UserForm(forms.ModelForm):
    confirm_pw = forms.CharField(widget=forms.PasswordInput(), label='Re-enter password')
    password = forms.CharField(widget=forms.PasswordInput())
    email = forms.EmailField()

    def clean(self):
        cleaned_data = super(UserForm, self).clean()
        password = cleaned_data.get("password")
        confirm_pw = cleaned_data.get("confirm_pw")

        email = self.cleaned_data.get('email')
        username = self.cleaned_data.get('username')
        if email and User.objects.filter(email=email).exclude(username=username).exists():
            raise forms.ValidationError("Email address already in use, please try a different one.")
        if password != confirm_pw:
            raise forms.ValidationError("Passwords do not match, try again.")

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'email', 'password')


class UserProfileForm(forms.ModelForm):
    dob = forms.DateField(label='Date of Birth')

    class Meta:
        model = UserProfile
        fields = ('dob', 'address', 'mobile')


class ProfileImageForm(forms.ModelForm):
    profile_pic = forms.ImageField(label='Upload a profile picture')

    class Meta:
        model = UserProfile
        fields = ['profile_pic']


class ItemForm(forms.ModelForm):
    end_datetime = forms.DateTimeField(label='End Date/Time', input_formats=['%d/%m/%Y %H:%M:%S'])
    title = forms.CharField(label='Item Name')

    class Meta:
        model = Item
        fields = ('title', 'description', 'base_price', 'end_datetime')


class ItemImageForm(forms.ModelForm):
    item_pic = forms.ImageField(label='Upload a item picture')

    class Meta:
        model = Item
        fields = ['item_pic']

nebula/webay/views.py
import datetime
from django.contrib.auth import logout as django_logout
from django.contrib.auth.decorators import user_passes_test, login_required
from django.contrib.auth.models import User
from django.http import HttpResponse, JsonResponse, QueryDict, Http404
from django.shortcuts import render, redirect
from django.utils import timezone
from webay.forms import UserForm, UserProfileForm, ProfileImageForm, ItemForm, ItemImageForm
from webay.models import UserProfile, Notification, Bid

from .models import Item


def index(request):
    context = {
        'items': Item.objects.filter(end_datetime__gte=datetime.datetime.now())[:5]
    }
    return render(request, 'webay/index.html', context)


def not_logged_in(user):
    return not user.is_authenticated


def closed_auctions(request):
    context = {
        'items': Item.objects.filter(end_datetime__lte=datetime.datetime.now()),
    }
    return render(request, 'webay/auctions.html', context)


def auctions(request):
    context = {
        'items': Item.objects.filter(end_datetime__gte=datetime.datetime.now())
    }
    return render(request, 'webay/auctions.html', context)


def item_view(request, item_id):
    if request.method == 'GET':
        auc_item = Item.objects.get(id=item_id)
        context = {
            'auction_item': auc_item,
            'auction_ended': auc_item.end_datetime > auc_item.start_datetime
        }
        return render(request, 'webay/item_detail.html', context)
    elif request.method == 'DELETE':
        Item.objects.get(id=item_id).delete()
        return HttpResponse(status=200)
    elif request.method == 'POST':
        request_data = request.POST
        highest_bid = Bid.objects.all().order_by('-amount').first().amount
        amount = request_data['amount']
        if highest_bid is not None:
            if float(highest_bid) > float(amount):
                return HttpResponse(status=400, content="Bid amount needs to be higher than £{}.".format(highest_bid))

        bid = Bid(
            amount=request_data['amount'],
            bid_datetime=timezone.now(),
            item=Item.objects.get(id=request_data['item_id']),
            user=request.user
        )
        bid.save()
        return HttpResponse(status=200)


def get_all_bids(request, item_id):
    item_chosen = Item.objects.get(id=item_id)
    bids = Bid.objects.all().order_by('-amount').filter(item=item_chosen).values('amount', 'bid_datetime', 'user')

    return JsonResponse(dict(bids=list(bids)))


@user_passes_test(not_logged_in, login_url='/profile')
def register(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileForm(data=request.POST)
        image_form = ProfileImageForm(data=request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            profile = profile_form.save(commit=False)
            profile.user = user
            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']
            profile.save()
            registered = True
        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileForm()
        image_form = ProfileImageForm()
    return render(request, 'webay/register.html',
                  {'user_form': user_form,
                   'profile_form': profile_form,
                   'image_form': image_form,
                   'registered': registered
                   })


@login_required
def get_my_items(request):
    return JsonResponse(dict(items=list(
        Item.objects.filter(user=request.user.id).values('id', 'title'))))


@login_required
def profile(request):
    user_form = UserForm()
    profile_form = UserProfileForm()
    image_form = ProfileImageForm()
    return render(request, 'webay/profile_form.html',
                  {
                      'user_form': user_form,
                      'profile_form': profile_form,
                      'image_form': image_form,
                  })


@login_required
def add_item(request):
    user = User.objects.get(pk=request.user.pk)
    if request.method == 'POST':
        item_form = ItemForm(data=request.POST)
        item_image_form = ItemImageForm(data=request.POST)
        if item_form.is_valid():
            item = item_form.save(commit=False)
            item.user = user
            item.start_datetime = timezone.now()
            if 'item_pic' in request.FILES:
                item.item_pic = request.FILES['item_pic']
            item.save()
            return redirect('webay:profile')  # Modify redirect so it goes to my items once you've finished that section

        else:
            print(item_form.errors, item_image_form.errors)
    else:
        item_form = ItemForm(initial={'user': user.pk})
        item_image_form = ItemImageForm()
    return render(request, 'webay/additem.html',
                  {
                      'itemForm': item_form,
                      'itemImageForm': item_image_form,
                  })


def get_user_details(request):
    if request.method == 'GET':
        user = User.objects.get(pk=request.user.id)
        profile = UserProfile.objects.get(user=user)
        return JsonResponse({
            'username': user.username,
            'first_name': user.first_name,
            'last_name': user.last_name,
            'email': user.email,
            'dob': profile.dob,
            'address': profile.address,
            'mobile': profile.mobile,
        })


def update_profile_pic(request):
    if 'img_file' in request.FILES:
        image_file = request.FILES['img_file']
        profile = UserProfile.objects.get(user=request.user)
        profile.profile_pic = image_file
        profile.save()
        return HttpResponse(status=204)
    else:
        return HttpResponse(status=403)


def update_profile_details(request):
    if request.method == 'PUT':
        user = User.objects.get(id=request.user.id)
        profile = UserProfile.objects.get(user=request.user)
        data = QueryDict(request.body)
        user.first_name = data['first_name']
        user.last_name = data['last_name']
        user.email = data['email']
        profile.dob = data['dob']
        profile.address = data['address']
        profile.mobile = data['mobile']
        user.save()
        profile.save()
        return HttpResponse(status=204)
    else:
        return HttpResponse(status=403)


def get_notifications(request):
    return JsonResponse(dict(notifications=list(
        Notification.objects.filter(recipient_id=request.user.id).values('id', 'read_message', 'item_id'))))


def get_notifications_message(request, id):
    notification = Notification.objects.filter(id=id).get();
    return HttpResponse(notification.message, content_type="text/html")


def get_number_unread_notifs(request):
    notification = Notification.objects.filter(recipient_id=request.user.id, read_message=0).count()
    return HttpResponse(notification)


def mark_notification_as_read(request, id):
    notification = Notification.objects.get(id=id)
    print(notification)
    notification.read_message = 1
    notification.save()
    return HttpResponse(status=200)


def display_profile_table(request):
    return render(request, "webay/profile_table.html")


def search(request):
    if request.method == 'POST':
        search = request.POST['search']
        print(search)
        try:
            itemSearch = Item.objects.all().filter(title__contains=search, end_datetime__gte=datetime.datetime.now()) | \
                         Item.objects.all().filter(description__contains=search, end_datetime__gte=datetime.datetime.now())
        except Item.DoesNotExist:
            raise Http404('Item does not exist')

        return render(request, 'webay/searchitems.html', {'itemSearch': itemSearch, })
    else:
        raise Http404('search not found')


@login_required
def logout(request):
    django_logout(request)
    return redirect('/')

nebula/webay/templates/webay/additem.html
{% extends "webay/base_profile.html" %}
{% block content %}
{% load crispy_forms_tags %}
<div class="jumbotron">
    <h3>Fill out the form to add an item.</h3>
    <form enctype="multipart/form-data" method="POST">
        {% csrf_token %}
        {{ itemForm|crispy }}
        {{ itemImageForm|crispy }}
        <input class="btn btn-info" type="submit" value="submit">
    </form>
</div>
{% endblock %}

nebula/webay/templates/webay/auctions.html
{% extends 'webay/base.html' %}
{% block body_block %}
<div id="searchBar" class="row pt-1">
    <form class="mx-2 my-auto w-50" method="post" action="{% url 'webay:search' %}">
        {% csrf_token %}
        <div class="input-group">
            <input id="search" type="text" name="search" class="form-control border border-right-0"
                   placeholder="Search...">
            <span class="input-group-append">
                <button id="searchButton" class="btn btn-outline-info my-sm-0" type="submit">Search</button>
              </span>
        </div>
    </form>
</div>
<div id="search-results">
    <h1> Auctions </h1>
    <div class="row">
        {% for item in items %}
        <div class="col">
            <img class="rounded-circle article-img" src="{{ item.user.profile_pic.url }}">
            <div class="media-body">
                <div class="article-metadata">
                    <a class="mr-2" href="#">{{ item.user }}</a>
                    <small class="text-muted">{{ item.start_datetime|date:"F d, Y" }}</small>
                </div>
                <h2><a href="{% url 'webay:item-detail' item.id %}">{{ item.title }}</a></h2>
                <img src="{{ item.item_pic.url }}" height="200px" width="250px">
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

nebula/webay/templates/webay/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <script defer src="/static/js/libs/jquery-3.4.1.min.js" charset="utf-8"></script>
    <script defer src="/static/js/libs/bootstrap.bundle.min.js" charset="utf-8"></script>
    <script type="module" src="/static/js/libs/js.cookie.min.js"></script>
    <!-- XDSoft DateTimePicker -->
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.min.css"
          integrity="sha256-DOS9W6NR+NFe1fUhEE0PGKY/fubbUCnOfTje2JMDw3Y=" crossorigin="anonymous"/>
    <script defer
            src="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.full.min.js"
            integrity="sha256-FEqEelWI3WouFOo2VWP/uJfs1y8KJ++FLh2Lbqc8SJk=" crossorigin="anonymous"></script>
    <script defer src="/static/js/script.js" charset="utf-8"></script>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/custom.css">

    <title>Webay</title>
</head>
<div>
    <nav class="navbar navbar-expand-xl navbar-dark bg-dark">
        <a href="{% url 'webay:homepage' %}" class="navbar-brand">Webay</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar5">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse" id="navbar5">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'webay:homepage' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'webay:auctions' %}">Open Auctions</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'webay:closedauctions' %}">Closed Auctions</a>
                </li>
            </ul>
            <ul class="navbar-nav">
                {% if user.is_authenticated %}
                <li class="nav-item dropdown">
                    <a class="nav-link" href="" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true"
                       aria-expanded="false">
                        Account
                    </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                        <a id="notificationNavLink" class="dropdown-item"
                           href="{% url 'webay:display_notifications' %}">Notifications</a>
                        <a class="dropdown-item" href="{% url 'webay:profile' %}">Settings</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'webay:logout' %}">Logout</a>
                    </div>
                </li>
                {% else %}
                <li class="nav-item">
                    <a id="login-btn" class="nav-link btn btn-info btn-sm text-white mr-2" role="button"
                       href="{% url 'webay:login' %}">Login</a>
                </li>
                <li class="nav-item">
                    <a id="register-btn" class="nav-link btn btn-info btn-sm text-white" role="button"
                       href="{% url 'webay:register' %}">Register</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>
    <div class="container">
        {% block body_block %}
        {% endblock %}
    </div>
</div>
</body>
</html>

nebula/webay/templates/webay/base_profile.html
{% extends 'webay/base.html' %}
{% block body_block %}
<div class="container">
    <div class="row pt-4">
        <p class="h2"> {{user.username}} </p>
    </div>
    <hr>
    <div class="row">
        <div class="col-3 text-center">
            <img class="img-fluid rounded-circle avatar" height="200" width="200" id="userProfilePic"
                 src="{{user.profile.profile_pic.url}}" alt="profile_picture"/>
            <form id="updateProfilePic" enctype="multipart/form-data" method="POST">
                {% csrf_token %}
                <input type="file" id="img_file" class="h6 small file-upload">
            </form>
            <div class="col">
                <a class="btn btn-outline-info text-info my-sm-2" href="{% url 'webay:profile' %}">Edit Profile</a>
            </div>
            <div class="col">
                <a class="btn btn-outline-info text-info my-sm-2" href="{% url 'webay:additem' %}">Add Item</a>

            </div>
            <div class="col">
                <a class="btn btn-outline-info text-info my-sm-2" href="{% url 'webay:display_my_items' %}">My Items</a>
            </div>
            <div class="col">
                <a id="notificationBtn" class="btn btn-outline-info text-info my-sm-2"
                   href="{% url 'webay:display_notifications' %}">Notifications</a>
            </div>
        </div>
        <div id="base_profile_content" class="col-9 pl-5">
            <div class="container">
                {% block content %}
                {% endblock %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

nebula/webay/templates/webay/index.html
{% extends 'webay/base.html' %}
{% block body_block %}
<div class="row">
    <h1> Current auctions: </h1>
</div>
<div class="row">
    <div id="itemCarouselControls" align="center" class="col carousel slide" data-ride="carousel"
         data-interval="3000">
        <div class="carousel-inner">
            {% for item in items %}
            <div class="carousel-item {% if forloop.counter == 1 %}active{% endif %}"
                 id="slide{{ forloop.counter }}">
                <div class="container">
                    <img class="rounded-circle article-img" src="{{ item.user.profile_pic.url }}">
                    <div class="media-body">
                        <div class="article-metadata">
                            <a class="mr-2" href="#">{{ item.user }}</a>
                            <small class="text-muted">{{ item.start_datetime|date:"F d, Y" }}</small>
                        </div>
                        <h2><a href="{% url 'webay:item-detail' item.id %}">{{ item.title }}</a></h2>
                        <img src="{{ item.item_pic.url }}" height="300px" width="300px">
                        <br>
                        <p><b>£{{ item.base_price }}</b></p>
                        <p>Time left: <b>{{ item.end_datetime|timeuntil:item.start_datetime }}</b></p>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
        <a class="carousel-control-prev" href="#itemCarouselControls" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#itemCarouselControls" role="button" data-slide="next">
            <span class="text-dark carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
</div>

{% endblock %}

nebula/webay/templates/webay/item.html
{% extends "webay/profile.html" %}
{% block content %}

<div class="container">
    <div class="jumbotron">
        <h3>Fill out the form to add an item.</h3>
        <form enctype="multipart/form-data" method="POST">
            {% csrf_token %}
            {{ itemForm.as_p }}
            {{ itemForm.end_datetime }}
            {{ ItemImageForm.as_p}}
            <input type="submit" value="submit">
        </form>
    </div>
</div>
{% endblock %}

nebula/webay/templates/webay/item_detail.html
{% extends 'webay/base.html' %}
{% block body_block %}
<div class="row" id="itemRow" item_id="{{ auction_item.id }}">
    <div class="col-sm pb-2">
        <img class="rounded-circle article-img" src="{{ auction_item.author.profile.image.url }}">
        <div class="media-body">
            <div class="article-metadata">
                <a class="mr-2" href="#">{{ auction_item.user }}</a>
                <small class="text-muted">{{ auction_item.start_datetime|date:"F d, Y" }}</small>
                <h2 class="article-title">{{ auction_item.title }}</h2>
                <img src="{{ auction_item.item_pic.url }}" height="300" width="300">
                <p class="article-content">{{ auction_item.description }}</p>
                {% if auction_ended %}
                <p> The auction ended on {{ auction_item.end_datetime }}.</p>
                {% else %}
                <p>Time left: <b>{{ auction_item.end_datetime|timeuntil:auction_item.start_datetime }}</b></p>
            </div>

            <div id="bidConditionalContent" auction_end="{{ auction_item.end_datetime|date:'F d, Y' }}">
                {% if auction_item.user == user %}
                <div>
                    <button class="btn btn-danger deleteItemBtn">Delete</button>
                </div>
                {% elif user.is_anonymous%}

                <p> You need to log in to be able to bid!</p>

                {% else %}

                <form id="bidForm" method="POST">
                    {% csrf_token %}
                    <br>
                    <p>{{user}}, enter your bid!</p>
                    Bid Amount : <input type="number" step="0.01" id="bidAmount" min="{{ auction_item.base_price }}">
                    <button class="btn btn-info" type="submit" name="submit"> Bid</button>
                </form>
                {% endif %}
                {% endif %}
            </div>
        </div>
    </div>
    <div class="col-sm">
        <table id="biddingList" class="table">
            <thead>
            <tr>
                <th scope="col">User:</th>
                <th scope="col">Amount:</th>
                <th scope="col">Date/Time:</th>
            </tr>
            </thead>
            <tbody>
            </tbody>
        </table>
    </div>
</div>

<script defer src="/static/js/bidding.js" charset="utf-8"></script>
{% endblock %}

nebula/webay/templates/webay/login.html
{% extends 'webay/base.html' %}
{% block body_block %}
{% load crispy_forms_tags %}
<div class="jumbotron">
    <h1>Login</h1>
    <form method="post" action="{% url 'webay:login' %}">
        {% csrf_token %}
        {{ form|crispy }}
        <input type="submit" value="Login">
    </form>
</div>
{% endblock %}

nebula/webay/templates/webay/profile_form.html
{% extends 'webay/base_profile.html' %}
{% block content %}
{% load crispy_forms_tags %}
<form id="updateProfileDetails" enctype="multipart/form-data" method="POST">
    {% csrf_token %}
    {{ user_form|crispy }}
    {{ profile_form|crispy }}
    <input class="btn btn-outline-info text-info my-sm-2" type="submit" value="Save">
</form>

<script defer src="/static/js/profile-script.js" charset="utf-8"></script>
{% endblock %}

nebula/webay/templates/webay/profile_table.html
{% extends 'webay/base_profile.html' %}
{% block content %}
<table id="profileTable" class="table">
    <thead>
    <tr>
        <th id="profileTableHeader" scope="col"></th>
    </tr>
    </thead>
    <tbody>
    </tbody>
</table>

<div class="modal fade" id="notificationModal" tabindex="-1" role="dialog" aria-labelledby="notificationModalLabel"
     aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="notificationModalLabel">Message</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                ...
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>
<script defer src="/static/js/profile-table-script.js" charset="utf-8"></script>
{% endblock %}

nebula/webay/templates/webay/register.html
{% extends "webay/base.html" %}
{% block body_block %}
{% load crispy_forms_tags %}
<div class="jumbotron">
    {% if registered %}
    <h1>Thank you for registering!</h1>
    {% else %}
    <h3>Fill out the form to register.</h3>
    <form enctype="multipart/form-data" method="POST">
        {% csrf_token %}
        {{ user_form|crispy }}
        {{ profile_form|crispy }}
        {{ image_form|crispy}}
        <input type="submit" value="Register">
    </form>

    {% endif %}
</div>
{% endblock %}

nebula/webay/templates/webay/searchitems.html
<h1>Search Results</h1>
<table class="table">
    <thead>
    <tr>
        <th scope="col">Image</th>
        <th scope="col">Item Title</th>
        <th scope="col">End Date/Time</th>
    </tr>
    </thead>
    <tbody>
    {% if itemSearch.count > 0 %}
    {% for item in itemSearch %}
    <tr>
        <td><img class="img-thumbnail img-fluid" height="100" width="100" src="{{ item.item_pic.url }}"/></td>
        <td><a href="{% url 'webay:item-detail' item.id %}">{{ item.title }}</a></td>
        <td>{{ item.end_datetime|date:"F d, Y" }}</td>
    </tr>
    {% endfor %}
    {% else %}
    <td> No results</td>
    {% endif %}
    </tbody>
</table>